# Documentation: https://github.com/roots/trellis#mail
mailhog_install_ssmtp: no
mail_admin: robeasthope@gmail.com
mail_hostname: didactic-guacamole.dev
mail_smtp_server: localhost:1025
ssmtp_auth_method: ""
ssmtp_start_tls: 'no'
ssmtp_tls: 'no'
